/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as ApiPublicScanRouteImport } from './routes/api/public/scan'
import { Route as ApiPublicEodCloseRouteImport } from './routes/api/public/eod-close'
import { Route as AuthenticatedDashboardSignalsRouteImport } from './routes/_authenticated/dashboard.signals'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardPerformanceRouteImport } from './routes/_authenticated/dashboard.performance'
import { Route as AuthenticatedDashboardOrdersRouteImport } from './routes/_authenticated/dashboard.orders'
import { Route as AuthenticatedDashboardLogsRouteImport } from './routes/_authenticated/dashboard.logs'
import { Route as AuthenticatedDashboardJobsRouteImport } from './routes/_authenticated/dashboard.jobs'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicScanRoute = ApiPublicScanRouteImport.update({
  id: '/api/public/scan',
  path: '/api/public/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEodCloseRoute = ApiPublicEodCloseRouteImport.update({
  id: '/api/public/eod-close',
  path: '/api/public/eod-close',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardSignalsRoute =
  AuthenticatedDashboardSignalsRouteImport.update({
    id: '/dashboard/signals',
    path: '/dashboard/signals',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardPerformanceRoute =
  AuthenticatedDashboardPerformanceRouteImport.update({
    id: '/dashboard/performance',
    path: '/dashboard/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardOrdersRoute =
  AuthenticatedDashboardOrdersRouteImport.update({
    id: '/dashboard/orders',
    path: '/dashboard/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardLogsRoute =
  AuthenticatedDashboardLogsRouteImport.update({
    id: '/dashboard/logs',
    path: '/dashboard/logs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardJobsRoute =
  AuthenticatedDashboardJobsRouteImport.update({
    id: '/dashboard/jobs',
    path: '/dashboard/jobs',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/dashboard/logs': typeof AuthenticatedDashboardLogsRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/signals': typeof AuthenticatedDashboardSignalsRoute
  '/api/public/eod-close': typeof ApiPublicEodCloseRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/dashboard/logs': typeof AuthenticatedDashboardLogsRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/signals': typeof AuthenticatedDashboardSignalsRoute
  '/api/public/eod-close': typeof ApiPublicEodCloseRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard/jobs': typeof AuthenticatedDashboardJobsRoute
  '/_authenticated/dashboard/logs': typeof AuthenticatedDashboardLogsRoute
  '/_authenticated/dashboard/orders': typeof AuthenticatedDashboardOrdersRoute
  '/_authenticated/dashboard/performance': typeof AuthenticatedDashboardPerformanceRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/signals': typeof AuthenticatedDashboardSignalsRoute
  '/api/public/eod-close': typeof ApiPublicEodCloseRoute
  '/api/public/scan': typeof ApiPublicScanRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard/jobs'
    | '/dashboard/logs'
    | '/dashboard/orders'
    | '/dashboard/performance'
    | '/dashboard/settings'
    | '/dashboard/signals'
    | '/api/public/eod-close'
    | '/api/public/scan'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/jobs'
    | '/dashboard/logs'
    | '/dashboard/orders'
    | '/dashboard/performance'
    | '/dashboard/settings'
    | '/dashboard/signals'
    | '/api/public/eod-close'
    | '/api/public/scan'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard/jobs'
    | '/_authenticated/dashboard/logs'
    | '/_authenticated/dashboard/orders'
    | '/_authenticated/dashboard/performance'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/signals'
    | '/api/public/eod-close'
    | '/api/public/scan'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicEodCloseRoute: typeof ApiPublicEodCloseRoute
  ApiPublicScanRoute: typeof ApiPublicScanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/scan': {
      id: '/api/public/scan'
      path: '/api/public/scan'
      fullPath: '/api/public/scan'
      preLoaderRoute: typeof ApiPublicScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/eod-close': {
      id: '/api/public/eod-close'
      path: '/api/public/eod-close'
      fullPath: '/api/public/eod-close'
      preLoaderRoute: typeof ApiPublicEodCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/signals': {
      id: '/_authenticated/dashboard/signals'
      path: '/dashboard/signals'
      fullPath: '/dashboard/signals'
      preLoaderRoute: typeof AuthenticatedDashboardSignalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/performance': {
      id: '/_authenticated/dashboard/performance'
      path: '/dashboard/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof AuthenticatedDashboardPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/orders': {
      id: '/_authenticated/dashboard/orders'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/logs': {
      id: '/_authenticated/dashboard/logs'
      path: '/dashboard/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof AuthenticatedDashboardLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/jobs': {
      id: '/_authenticated/dashboard/jobs'
      path: '/dashboard/jobs'
      fullPath: '/dashboard/jobs'
      preLoaderRoute: typeof AuthenticatedDashboardJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardJobsRoute: typeof AuthenticatedDashboardJobsRoute
  AuthenticatedDashboardLogsRoute: typeof AuthenticatedDashboardLogsRoute
  AuthenticatedDashboardOrdersRoute: typeof AuthenticatedDashboardOrdersRoute
  AuthenticatedDashboardPerformanceRoute: typeof AuthenticatedDashboardPerformanceRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardSignalsRoute: typeof AuthenticatedDashboardSignalsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardJobsRoute: AuthenticatedDashboardJobsRoute,
  AuthenticatedDashboardLogsRoute: AuthenticatedDashboardLogsRoute,
  AuthenticatedDashboardOrdersRoute: AuthenticatedDashboardOrdersRoute,
  AuthenticatedDashboardPerformanceRoute:
    AuthenticatedDashboardPerformanceRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardSignalsRoute: AuthenticatedDashboardSignalsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicEodCloseRoute: ApiPublicEodCloseRoute,
  ApiPublicScanRoute: ApiPublicScanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
